### ISSUE TITLE
could not obtain access token

### ISSUE THREAD

**Issue by nrbunn** [vymiyai/spring-oauth2-discord#1]
I'm getting could not obtain access token. It looks like you posted at the below link saying you figured something out. But i'm not understanding it. Any help?
https://www.reddit.com/r/springsource/comments/6kb9ih/spring_security_oauth2_and_discord/

**Comment by vymiyai** [comment]
Hello there, sorry for not replying before.

Hopefully, you have solved your issue, but in case you haven't yet, I've updated the repository with the code that worked for me.
